### ISSUE TITLE
Improve TS Types

### ISSUE THREAD

**Issue by lishaduck** [mpizenberg/elm-solve-deps-wasm#2]
Hello! Coming here from node-elm-review, I'm working on enabling `noImplictAny` on the codebase, and it came to my attention that there are some types that could be improved.
I'm not sure how they're generated, as I'm not particularly familiar with Rust, but it seems to me that this declaration needs updating:
`export function solve_deps(project_elm_json_str: string, use_test: boolean, additional_constraints_str: any, js_fetch_elm_json: Function, js_list_available_versions: Function): any;` should rather be `export function solve_deps(project_elm_json_str: string, use_test: boolean, additional_constraints_str: Record<string, string>, js_fetch_elm_json: (pkg: string, version: string) => string, js_list_available_versions: (pkg: string) => string[]): string;`.
I can explicitly set it in elm-review, but it seems that it would be a worthwhile enhancement for all of the consumers if it was changed here.

**Comment by mpizenberg** [comment]
Hi @lishaduck. So I’m not entirely sure what the `solve_deps` function you mention refers to. In this repo, this function only exists as a rust function https://github.com/mpizenberg/elm-solve-deps-wasm/blob/6e304ab456efa3d934c525137cd5354c9bfd15be/src/lib.rs#L45 defined as follows:
```rust
/// Solve dependencies for the provided `elm.json`.
///
/// Include also test dependencies if `use_test` is `true`.
/// It is possible to add additional constraints.
/// The caller is responsible to provide implementations to be able to fetch the `elm.json` of
/// dependencies, as well as to list existing versions (in prefered order) for a given package.
#[wasm_bindgen]
pub fn solve_deps(
    project_elm_json_str: &str,
    use_test: bool,
    // additional_constraints_str: &HashMap<String, Constraint>,
    additional_constraints_str: JsValue,
    // js_fetch_elm_json(pkg: &str, version: &str) -> String;
    js_fetch_elm_json: js_sys::Function,
    // js_list_available_versions(pkg: &str) -> Vec<String>;
    js_list_available_versions: js_sys::Function,
) -> Result<JsValue, JsValue> {
   ...
}
```

As far as I remember, I was constrained to have the type `JsValue` in there to accept data that cannot be bridged natively at the WASM frontier, or automatically handled by the wasmbindgen tool.

I suppose the typing annotation you mention comes from some automated generation when I package the wasm binary into an npm package. I also suppose that the `any` you refer to comes from that automated tool. And since I’m not too familiar with JS/TS, I didn’t make much effort trying to see if there was a way to customize these automatically generated annotations.

I don’t have the time to dive into it now, but if you or anyone want to give it a try, I would accept a PR that improve the situation. As long as it’s reasonably maintainable.

**Comment by lishaduck** [comment]
Ok, I see now. JsValue becomes `any`, and `js_sys::Function` becomes `Function`. I'll take a look at the bundling, I would assume there's a way to give the more specific type. Thanks for the info!

**Comment by mpizenberg** [comment]
As you can see, the last version of this was two years ago and I haven’t had to update it since no bug surfaced. I haven’t worked in JS/Rust/Wasm in the past two years (mostly python stuff) so I haven’t followed closely. But if there are improvements there, the most obvious place to find them would be anything related to wasmbindgen https://github.com/rustwasm/wasm-bindgen. I’d look there first if I were looking into it.

**Comment by lishaduck** [comment]
Ok, it took a bit, but I think I have something working!
I just need to wait for wasm-pack to finish installing so I can check the generated code.

**Comment by lishaduck** [comment]
Huh. It didn't close this issue.
Also, can you publish a new `elm-solve-deps-wasm` to NPM?

**Comment by mpizenberg** [comment]
Thanks for the improvements you did!
Since we publish this still as with the node target, I guess there is no breaking change in the API?
So since it’s mainly a types and docs improvements, we can go from v1.0.2 to v1.0.3?

**Comment by lishaduck** [comment]
> Thanks for the improvements you did! Since we publish this still as with the node target, I guess there is no breaking change in the API? So since it’s mainly a types and docs improvements, we can go from v1.0.2 to v1.0.3?

_Technically,_ I'd think this is breaking, but there are a grand total of two consumers, neither of which it breaks, so I think a patch is fine. Very few people care about type SemVer in JS, and those who do aren't going to complain about this (as they don't use this). ~~I might complain if I hadn't written it, and tried to update, but I did 😁~~ (nah, I'd probably be too excited to complain 😜)

**Comment by mpizenberg** [comment]
Ahah right it's not breaking JS but it's breaking TS. Let's go for a major
bump then. And elm test and elm review can consciously upgrade instead of
implicitly.

**Comment by lishaduck** [comment]
> Ahah right it's not breaking JS but it's breaking TS. Let's go for a major bump then. And elm test and elm review can consciously upgrade instead of implicitly.

I realized that reactions don't notify, so here's my approval: 👍

**Comment by mpizenberg** [comment]
Published https://www.npmjs.com/package/elm-solve-deps-wasm/v/2.0.0

**Comment by lishaduck** [comment]
> Published https://www.npmjs.com/package/elm-solve-deps-wasm/v/2.0.0

Yay! Thanks!
